### ISSUE TITLE
Publish backend code

### ISSUE THREAD

**Issue by sander** [IBM/datascienceontology#16]
Thank you for sharing this interesting project.

If I’m not mistaken, `datascienceontology-frontend` uses a CouchDB + Node.js backend at `api.datascienceontology.org`. I could not find the source code for it however. Is it publicly available somewhere for collaboration?

**Comment by epatters** [comment]
Hi @sander, thanks for your interest in the project.

That is correct. The backend at `api.datascienceontology.org` is a simple Node.js app that sits in front of CouchDB and a Redis cache. I have not publicly released it but I can certainly do so if there is interest.

**Comment by epatters** [comment]
BTW, for a while I've been considering migrating to a graph database, possibly [Dgraph](https://dgraph.io/), to enable more flexible querying, but I haven't been able to dedicate the time for that yet.

**Comment by epatters** [comment]
OK, I've sanitized the Git history and released the backend at [epatters/datascienceontology-backend](https://github.com/epatters/datascienceontology-backend). The source code for the REST API and the CouchDB config is all there.

The OpenWhisk actions for generating the wiring diagrams are not self-contained, but this is a start. Let's track any followup issues at the new repo.

**Comment by sander** [comment]
That was quick, thank you!
