### ISSUE TITLE
DSO browser should link to github repo

### ISSUE THREAD

**Issue by ioana-blue** [IBM/datascienceontology#3]
First page here:
https://www.datascienceontology.org/

should link to this repo with some "contribute-here" type of heading. 

One option: a "Contribute" button aligned with the Browse, Learn More  ones.

**Comment by ioana-blue** [comment]
The Contribute button could point to this page:  https://www.datascienceontology.org/help/contribute

**Comment by epatters** [comment]
Good idea! Done.
