### ISSUE TITLE
Use consistent terminology in ontology and frontend

### ISSUE THREAD

**Issue by epatters** [IBM/datascienceontology#4]
After much discussion, we've decided to adopt PLT-style terminology (types, functions, etc.) instead of category-theoretic terminology (objects, morphisms, etc.) for the ontology. This choice is already reflected in the [frontend](https://github.com/ibm/datascienceontology-frontend), but not in the ontology data itself. That may seem a small matter but it creates a non-negligble barrier for new contributors.

To fix this, we need to update:

- the JSON schemas for concepts and annotations
- the concepts and annotations themselves
- the downstream tools that consume the ontology

**Comment by epatters** [comment]
I'm going to do this in two steps:

1. Update the JSON schemas for concept and annotations, and all downstream tools
2. Update the S-expressions themselves, and all downstream tools

**Comment by ioana-blue** [comment]
Sounds good. Clarifying question: what's `S-expression`?

**Comment by epatters** [comment]
By "S-expression" I mean the definitions appearing in function annotations, e.g., in [read-sql-table](https://github.com/IBM/datascienceontology/blob/master/annotation/python/pandas/read-sql-table.yml)

```yaml
[
  compose,
  [ construct, [ pair, sql-table-database, sql-table-name ] ],
  read-table
]
```

So instead of `pair`, this will say `apply`, etc.

**Comment by epatters** [comment]
Part 1 is finished!

**Comment by epatters** [comment]
Step 2 is finished. We're done here.
